[package]
name = "edaberu"
version = "0.1.0"
edition.workspace = true

[dependencies]
edaberu_core.workspace = true
twilight-gateway.workspace = true
twilight-model.workspace = true
twilight-http.workspace = true
twilight-cache-inmemory.workspace = true
songbird.workspace = true
symphonia.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
